"""add socials table

Revision ID: 035af6428993
Revises: 9e7be980b1c1
Create Date: 2026-01-02 16:44:24.138053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035af6428993'
down_revision = '9e7be980b1c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('socials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('social_name'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('socials')
    # ### end Alembic commands ###
