"""set up relation between institutes and project

Revision ID: 17d2ffb07487
Revises: ace4dc06894f
Create Date: 2025-11-13 11:28:44.237193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d2ffb07487'
down_revision = 'ace4dc06894f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institute_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_projects_institute_id_institute'), 'institute', ['institute_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_projects_institute_id_institute'), type_='foreignkey')
        batch_op.drop_column('institute_id')

    # ### end Alembic commands ###
