"""add technologies table

Revision ID: 244eed3b6c76
Revises: 0488c1cd66db
Create Date: 2025-12-31 12:03:57.220078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244eed3b6c76'
down_revision = '0488c1cd66db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=False),
    sa.Column('tech_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logo'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('tech_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('technologies')
    # ### end Alembic commands ###
