"""create project section table

Revision ID: 529a3411f830
Revises: e4b6dccfbab6
Create Date: 2025-11-13 09:37:50.760494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529a3411f830'
down_revision = 'e4b6dccfbab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project-sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('img_1', sa.String(), nullable=True),
    sa.Column('img_2', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project-sections')
    # ### end Alembic commands ###
