"""update projects table

Revision ID: 81fdffb1cf8c
Revises: 244eed3b6c76
Create Date: 2025-12-31 12:33:29.754164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81fdffb1cf8c'
down_revision = '244eed3b6c76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('intro', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('web_url', sa.String(), nullable=True),
    sa.Column('git_url', sa.String(), nullable=True),
    sa.CheckConstraint('(end_date is NULL) or (end_date > start_date)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('git_url'),
    sa.UniqueConstraint('img'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('web_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
