"""add institute table

Revision ID: 979dfa4013fb
Revises: 839198255650
Create Date: 2025-11-12 14:38:01.660820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979dfa4013fb'
down_revision = '839198255650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('institute')
    # ### end Alembic commands ###
