"""update sections table with a relationship with projects

Revision ID: d4988f59443e
Revises: ffa817c5bca3
Create Date: 2025-11-13 14:44:20.924691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4988f59443e'
down_revision = 'ffa817c5bca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project-sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_project-sections_project_id_projects'), 'projects', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project-sections', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_project-sections_project_id_projects'), type_='foreignkey')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###
