"""create api table

Revision ID: e4b6dccfbab6
Revises: d8894f6c2dd2
Create Date: 2025-11-13 09:18:29.988276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b6dccfbab6'
down_revision = 'd8894f6c2dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('git_link', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('web_link', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('web_link')
        batch_op.drop_column('git_link')

    op.drop_table('apis')
    # ### end Alembic commands ###
