"""create institute table and update project table

Revision ID: ea7d8efb9339
Revises: 035af6428993
Create Date: 2026-01-03 14:47:44.795932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea7d8efb9339'
down_revision = '035af6428993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logo'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institute_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_projects_institute_id_institutes'), 'institutes', ['institute_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_projects_institute_id_institutes'), type_='foreignkey')
        batch_op.drop_column('institute_id')

    op.drop_table('institutes')
    # ### end Alembic commands ###
